name: Publish Website to Web Hosting
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: waws-prod-se1-007.ftp.azurewebsites.windows.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: ./site/wwwroot/
          protocol: ftp
          port: 990
          exclude: |
            **/.html*
            **/.js*
            **/.css*
            **/.txt*
            **/.php*
            **/.jpg*
            **/.png*
            **/.woff*
            **/.woff2*
            **/.gif*
            **/.mp3*
            **/.mp4*
